
CREATE TABLE USER
(ID INT NOT NULL,
Bruker VARCHAR(15) NOT NULL,
Passord VARCHAR(30) NOT NULL,
CONSTRAINT User_PK PRIMARY KEY(ID)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE COURSE
(CourseID INT NOT NULL,
Code VARCHAR(7) NOT NULL,
Name VARCHAR(60) NOT NULL,
CONSTRAINT Course_PK PRIMARY KEY(CourseID)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE LECTURE
(LectureID INT NOT NULL,
CourseID INT NOT NULL,
Number INT NOT NULL,
Name VARCHAR(60) NOT NULL,
CONSTRAINT Lecture_PK PRIMARY KEY(LectureID),
CONSTRAINT Lecture_FK FOREIGN KEY(CourseID) REFERENCES COURSE(CourseID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TOPIC
(TopicID INT NOT NULL,
LectureID INT NOT NULL,
Number INT NOT NULL,
Name VARCHAR(60) NOT NULL,
CONSTRAINT Topic_PK PRIMARY KEY(TopicID),
CONSTRAINT Topic_FK FOREIGN KEY(LectureID) REFERENCES LECTURE(LectureID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE QUESTION
(QuestionID INT NOT NULL,
TopicID INT NOT NULL,
UserID INT NOT NULL,
Question TEXT NOT NULL,
CONSTRAINT Question_PK PRIMARY KEY(QuestionID),
CONSTRAINT QuestionTopic_FK FOREIGN KEY(TopicID) REFERENCES TOPIC(TopicID) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT QuestionUser_FK FOREIGN KEY(UserID) REFERENCES USER(ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE RATING
(RatingID INT NOT NULL,
TopicID INT NOT NULL,
UserID INT NOT NULL,
Stars INT(1) NOT NULL,
CONSTRAINT Rating_PK PRIMARY KEY(RatingID),
CONSTRAINT Rating_Topic_FK FOREIGN KEY(TopicID) REFERENCES TOPIC(TopicID) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT Rating_User_FK FOREIGN KEY(UserID) REFERENCES USER(ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET=latin1;
