language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      
before_install: cd Program

notifications:
  email: false
  slack: prodoteam:ybnDKIhpodUlM0ZRwMh5qqug
