language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      
before_install: cd Program

notifications:
  email: false
  slack: prodoteam:ybnDKIhpodUlM0ZRwMh5qqug

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
